### ISSUE TITLE
rails 5.0.0 alpha NoMethodError: undefined method `remote_addr' for nil:NilClass

### ISSUE THREAD

**Issue by FlowerWrong** [rails/web-console#155]
```ruby
WebConsole::RequestTest#test_#from_whitelisted_ip?_is_falsy_for_blacklisted_IPs_via_whitelisted_proxies:
NoMethodError: undefined method `remote_addr' for nil:NilClass
    /home/yang/.rvm/gems/ruby-2.2.2/bundler/gems/rails-9b7ecf0d6d28/actionpack/lib/action_dispatch/middleware/remote_ip.rb:112:in `calculate_ip'
    /home/yang/.rvm/gems/ruby-2.2.2/bundler/gems/rails-9b7ecf0d6d28/actionpack/lib/action_dispatch/middleware/remote_ip.rb:145:in `to_s'
    /home/yang/dev/ruby/gems/web-console/lib/web_console/request.rb:29:in `strict_remote_ip'
    /home/yang/dev/ruby/gems/web-console/lib/web_console/request.rb:21:in `from_whitelited_ip?'
    /home/yang/dev/ruby/gems/web-console/test/web_console/request_test.rb:30:in `block in <class:RequestTest>'
```
I exec `rake test`. There are 23 errors.
```ruby
65 runs, 2603 assertions, 1 failures, 23 errors, 0 skips
```

**Comment by gsamokovarov** [comment]
Absolutely correct. Thanks for the quick report.

Seems that https://github.com/rails/rails/commit/07b2ff03d04656faccc68c83541b06e318a36ed7 breaked it, but that's what we get for relying on Rails internals knowledge. Will look it up.
