### ISSUE TITLE
NameError: uninitialized constant Mime::HTML

### ISSUE THREAD

**Issue by AmanShurafa** [rails/web-console#243]
acceptable_content_type? is generating this error:

```
NameError: uninitialized constant Mime::HTML
	from /ruby_gems/gems/web-console-2.3.0/lib/web_console/middleware.rb:58:in `acceptable_content_type?'
	from /ruby_gems/gems/web-console-2.3.0/lib/web_console/middleware.rb:36:in `block in call'
	from /ruby_gems/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
	from /ruby_gems/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
	from /ruby_gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
	from /ruby_gems/gems/railties-5.1.0/lib/rails/rack/logger.rb:36:in `call_app'
	from /ruby_gems/gems/railties-5.1.0/lib/rails/rack/logger.rb:26:in `call'
	from /ruby_gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
	from /ruby_gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/request_id.rb:25:in `call'
	from /ruby_gems/gems/rack-2.0.2/lib/rack/method_override.rb:22:in `call'
	from /ruby_gems/gems/rack-2.0.2/lib/rack/runtime.rb:22:in `call'
	from /ruby_gems/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
	from /ruby_gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
	from /ruby_gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/static.rb:125:in `call'
	from /ruby_gems/gems/rack-2.0.2/lib/rack/sendfile.rb:111:in `call'
	from /ruby_gems/gems/railties-5.1.0/lib/rails/engine.rb:522:in `call'
	from /ruby_gems/gems/rack-2.0.2/lib/rack/urlmap.rb:68:in `block in call'
	from /ruby_gems/gems/rack-2.0.2/lib/rack/urlmap.rb:53:in `each'
	from /ruby_gems/gems/rack-2.0.2/lib/rack/urlmap.rb:53:in `call'
	from /ruby_gems/gems/capybara-2.12.0/lib/capybara/server.rb:43:in `call'
	from /ruby_gems/gems/rack-2.0.2/lib/rack/handler/webrick.rb:86:in `service'
	from /usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
	from /usr/local/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
	from /usr/local/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
```

Ruby 2.4.0 & Rails 5.1.0

**Comment by gsamokovarov** [comment]
Update `web-console` to the latest version. Beware that just `bundle update web-console` may not work if you have an explicit version constraint in the `Gemfile`. Removing it should let you `bundle update web-console`. Rails 5 is using`Mime` version that is incompatible with `web-console` v2 series.
