### ISSUE TITLE
Failing tests with Ruby 2.7

### ISSUE THREAD

**Issue by pvalena** [rails/web-console#299]
While executing tests in Fedora (we're running tests for packaged gems).

All of them seem to fail with same error:
```
DEBUG: WebConsole::IntegrationTest#test_Exception#bindings_returns_all_the_bindings_for_a_custom_error:
DEBUG: NameError: uninitialized constant WebConsole::IntegrationTest::SourceLocation
DEBUG:     /builddir/build/BUILD/web-console-4.0.4web-console (4.0.4) test/web_console/integration_test.rb:16:in `block in <class:IntegrationTest>'
DEBUG:     minitest (5.14.1) lib/minitest/test.rb:98:in `block (3 levels) in run'
DEBUG:     minitest (5.14.1) lib/minitest/test.rb:195:in `capture_exceptions'
DEBUG:     minitest (5.14.1) lib/minitest/test.rb:95:in `block (2 levels) in run'
DEBUG:     minitest (5.14.1) lib/minitest.rb:272:in `time_it'
DEBUG:     minitest (5.14.1) lib/minitest/test.rb:94:in `block in run'
DEBUG:     minitest (5.14.1) lib/minitest.rb:367:in `on_signal'
DEBUG:     minitest (5.14.1) lib/minitest/test.rb:211:in `with_info_handler'
DEBUG:     minitest (5.14.1) lib/minitest/test.rb:93:in `run'
DEBUG:     minitest (5.14.1) lib/minitest.rb:1029:in `run_one_method'
DEBUG:     minitest (5.14.1) lib/minitest.rb:341:in `run_one_method'
DEBUG:     minitest (5.14.1) lib/minitest.rb:328:in `block (2 levels) in run'
DEBUG:     minitest (5.14.1) lib/minitest.rb:327:in `each'
DEBUG:     minitest (5.14.1) lib/minitest.rb:327:in `block in run'
DEBUG:     minitest (5.14.1) lib/minitest.rb:367:in `on_signal'
DEBUG:     minitest (5.14.1) lib/minitest.rb:354:in `with_info_handler'
DEBUG:     minitest (5.14.1) lib/minitest.rb:326:in `run'
DEBUG:     minitest (5.14.1) lib/minitest.rb:164:in `block in __run'
DEBUG:     minitest (5.14.1) lib/minitest.rb:164:in `map'
DEBUG:     minitest (5.14.1) lib/minitest.rb:164:in `__run'
DEBUG:     minitest (5.14.1) lib/minitest.rb:141:in `run'
DEBUG:     minitest (5.14.1) lib/minitest.rb:68:in `block in autorun'
DEBUG: rails test /builddir/build/BUILD/web-console-4.0.4/usr/share/gems/gems/web-console-4.0.4/test/web_console/integration_test.rb:13
DEBUG: Finished in 0.424797s, 197.7414 runs/s, 115.3491 assertions/s.
DEBUG: 84 runs, 49 assertions, 12 failures, 36 errors, 0 skips
```
Tests log: https://git.io/JJjej

Also there's another warning (might be good hint):
```
DEBUG: /usr/share/gems/gems/minitest-5.14.1/lib/minitest.rb:367: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead
```

**Comment by voxik** [comment]
It seems you are mixing web-console-3.5.1 with web-console-4.0.4
