### ISSUE TITLE
NameError: constant WebConsole::SourceLocation not defined

### ISSUE THREAD

**Issue by masterkain** [rails/web-console#320]
I'm not entirely sure what's going on here but I have this in a Rails 7.0.3.1 app:

```
 NameError: constant WebConsole::SourceLocation not defined

           source_location = SourceLocation.new(binding)
                             ^^^^^^^^^^^^^^
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/exception_mapper.rb:51:in `block in guess_the_first_application_binding'
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/exception_mapper.rb:50:in `each'
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/exception_mapper.rb:50:in `find'
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/exception_mapper.rb:50:in `guess_the_first_application_binding'
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/exception_mapper.rb:30:in `first'
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/session.rb:48:in `initialize'
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/session.rb:34:in `new'
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/session.rb:34:in `from'
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:30:in `block in call'
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `catch'
 	from /bundle/vendor/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/actionpack-7.0.3.1/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/rack/logger.rb:40:in `call_app'
 	from /bundle/vendor/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/rack/logger.rb:25:in `block in call'
 	from /bundle/vendor/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/tagged_logging.rb:114:in `block in tagged'
 	from /bundle/vendor/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/tagged_logging.rb:38:in `tagged'
 	from /bundle/vendor/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/tagged_logging.rb:114:in `tagged'
 	from /bundle/vendor/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/rack/logger.rb:25:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:11:in `block in call'
 	from /bundle/vendor/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/logger_silence.rb:18:in `block in silence'
 	from /bundle/vendor/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/logger_thread_safe_level.rb:43:in `log_at'
 	from /bundle/vendor/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/logger_silence.rb:18:in `silence'
 	from /bundle/vendor/ruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:11:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/actionpack-7.0.3.1/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/actionpack-7.0.3.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/activesupport-7.0.3.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/actionpack-7.0.3.1/lib/action_dispatch/middleware/server_timing.rb:20:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/actionpack-7.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/actionpack-7.0.3.1/lib/action_dispatch/middleware/static.rb:23:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/actionpack-7.0.3.1/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/engine.rb:530:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/newrelic_rpm-8.9.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/puma-5.6.4/lib/puma/configuration.rb:252:in `call'
 	from /bundle/vendor/ruby/3.1.0/gems/puma-5.6.4/lib/puma/request.rb:77:in `block in handle_request'
 	from /bundle/vendor/ruby/3.1.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
 	from /bundle/vendor/ruby/3.1.0/gems/puma-5.6.4/lib/puma/request.rb:76:in `handle_request'
 	from /bundle/vendor/ruby/3.1.0/gems/puma-5.6.4/lib/puma/server.rb:441:in `process_client'
 	from /bundle/vendor/ruby/3.1.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by FaithAdekunle** [comment]
I am having the same error.

**Comment by dneighbors** [comment]
Same issue.

**Comment by dotgrid** [comment]
Same thing for me 😞

**Comment by gsamokovarov** [comment]
Can you give me some context, so I can track this down. Maybe your specific Gemfile? When does this happen? During error, during boot?

**Comment by okarny** [comment]
@gsamokovarov this happens at `bundle install` and its the web-console gem as seen in the error above. @masterkain correct me if i'm wrong but when I removed the gem these issues went away.

**Comment by gsamokovarov** [comment]
Do you folks (@dotgrid ) happen to have `new_relic` as well?

**Comment by okarny** [comment]
@gsamokovarov I use new_relic.

**Comment by dotgrid** [comment]
> Do you folks (@dotgrid ) happen to have `new_relic` as well?

I'm not using New Relic on this project, no.

Let me know if I can provide any other info to help troubleshoot?

**Comment by denys-chaikovskyi** [comment]
Having same issue with: 
```
web-console 4.2.0
rails 7.0.4
ruby 3.2.2
```

**Comment by domq** [comment]
Same issue with
```
web-console 4.2.0
rails 7.0.4.3
ruby 3.1.4
```

**Comment by domq** [comment]
I know next to nothing to Ruby on Rails, but seems like the cause could be as simple as `class SourceLocation` in `lib/web_console/source_location.rb` missing a `module WebConsole` wrapper. At any rate, changing that file manually in the `vendor` directory from

```
# frozen_string_literal: true

class SourceLocation
#...
end
```
to

```
# frozen_string_literal: true

module WebConsole
  class SourceLocation
  #...
  end
end
```

fixes the problem for me.

**Comment by domq** [comment]
[Aaand this looks fixed already](https://github.com/rails/web-console/commit/dc3df04a921533f99894e5843a45cb518360ad30).

Upgrading `web-console` to version 4.2.1 with
```
bundle update web-console
```

fixes the problem as well.
